ktor:
  application:
    modules:
      - example.com.ApplicationKt.module
  deployment:
    port: 8080
    # SSL configuration for Facebook Authentication
    sslPort: 8443
    watch:
      - classes
      - resources
  development: true
  security:
    ssl:
      keyStore: "/Users/rodrigomartins/Desktop/Dev/Active-Hive-ktor-web-android/ktor-server/keystore.jks"
      keyAlias: sampleAlias
      keyStorePassword: password123
      privateKeyPassword: password123


storage:
  user: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  name: $POSTGRES_DB
  host: $POSTGRES_HOST

jwt:
  domain: "http://0.0.0.0:8080"
  issuer: "http://0.0.0.0:8080"
  audience: "users"
  realm: "ktor-backend"
  secret: $JWT_SECRET

smtp:
  host: $SMTP_HOST
  port: $SMTP_PORT
  username: $SMTP_USERNAME
  password: $SMTP_PASSWORD
  from: $SMTP_FROM
  production: false # Set to true in production
